#!/bin/bash
cd /var/www/html/COEPLirary

php /usr/local/bin/composer install

sudo chmod -R 777 storage public vendor bootstrap database

php /usr/local/bin/composer dump-autoload
php artisan config:clear
