#!/bin/bash
cd /var/www/html/COEPLibrary

php /usr/local/bin/composer install

sudo chmod -R 777 storage public vendor bootstrap database

php /usr/local/bin/composer dump-autoload

php artisan storage:link
php artisan config:clear
